### PR TITLE
Use jsk_travis

### PR DESCRIPTION
**Pull request by garaemon**

### CODE REVIEW

**Comment by garaemon** [comment]
docker is dead?
```
2015/01/26 13:33:08 dial unix /var/run/docker.sock: no such file or directory

```

**Comment by garaemon** [comment]
@k-okada Could you reboot jenkins?

**Comment by k-okada** [comment]
both jenkins and docker demon are restarted

--
◉ Kei Okada

**Comment by garaemon** [comment]
thanks!

**Pull request merged**
