### PR TITLE
check 'after_run_hook' before execute-pddl.l exits

### PR DESCRIPTION
**Pull request by k-okada**
@furushchev 

check 'after_run_hook' before execute-pddl.l exits, by running test code at 100hz

https://github.com/jsk-ros-pkg/jsk_planning/blob/0.1.8/task_compiler/euslisp/execute-pddl.l exits with 0 or 1 and this node is executed by https://github.com/jsk-ros-pkg/jsk_planning/blob/0.1.8/task_compiler/launch/execute-pddl.launch#L21 (with required tag)
the reason https://github.com/jsk-ros-pkg/jsk_roseus/pull/501#issuecomment-281628408 fails is because it exits before 'after_run_hook' tests (https://github.com/jsk-ros-pkg/jsk_planning/blob/0.1.8/task_compiler/test/test-task-compiler.l#L42), I think.

### CODE REVIEW

**Comment by furushchev** [comment]
@k-okada +100. Great! I checked on local machine (indigo / kinetic) and new works 10 / 10 successfully.
As a result, we were very lucky that we can pass this test? Anyway thank you very much!

**Comment by k-okada** [comment]
Which one do you prefar, this or #57
And why you set this node as required?

**Comment by furushchev** [comment]
@k-okada

>  And why you set this node as required?

If required is set to true, `roslaunch` finishes after each demo performance, which is useful for scripting multiple demos.

**Comment by furushchev** [comment]
@k-okada Sorry, I partially answered. I prefer this pull request, because no launch file is modified.

**Pull request closed without merging**
