### PR TITLE
[task_compiler] add task_compiler test

### PR DESCRIPTION
**Pull request by furushchev**
with advice of https://github.com/jsk-ros-pkg/jsk_planning/pull/25

### CODE REVIEW

**Comment by furushchev** [comment]
travis failed.

```
/opt/ros/hydro/share/downward/scripts/plan: line 40: time: command not found
```

waiting for merge https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/35

**Comment by furushchev** [comment]
waiting after merge https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/36

**Comment by furushchev** [comment]
test failed only on jade. `roseus_smach` package is not yet released?
```
[task_compiler] CMake Error at /opt/ros/jade/share/catkin/cmake/catkinConfig.cmake:75 (find_package): 

[task_compiler]   Could not find a package configuration file provided by "roseus_smach" with 

[task_compiler]   any of the following names:                                   

[task_compiler]                                                                 

[task_compiler]     roseus_smachConfig.cmake                                    

[task_compiler]     roseus_smach-config.cmake                                   

[task_compiler]                                                                 

[task_compiler]   Add the installation prefix of "roseus_smach" to CMAKE_PREFIX_PATH or set 

[task_compiler]   "roseus_smach_DIR" to a directory containing one of the above files.  If 

[task_compiler]   "roseus_smach" provides a separate development package or SDK, be sure it 

[task_compiler]   has been installed.                                           

[task_compiler] Call Stack (most recent call first):                            

[task_compiler]   CMakeLists.txt:4 (find_package)                               

[task_compiler]                                                                 

[task_compiler]                                                                 

[task_compiler] -- Configuring incomplete, errors occurred!  
```

**Comment by k-okada** [comment]
currently roseus_smach is ignored at
https://github.com/tork-a/jsk_roseus-release/blob/master/jade.ignored

if all depended packages are released, we can remove this setting

--
◉ Kei Okada

**Comment by k-okada** [comment]
released  https://github.com/ros/rosdistro/pull/9839

**Comment by k-okada** [comment]
ok, finally roseus_smach has been released.
http://www.ros.org/debbuild/jade.html?q=roseus

--
◉ Kei Okada

**Comment by furushchev** [comment]
@k-okada Thank you. now I reverted temporal commit.
Currently this pr has dirty commits, so I'll rebase when all tests passes.

**Comment by furushchev** [comment]
now i rebased this PR. this commit should pass the test.

**Comment by k-okada** [comment]
since I have updated master branch and broken this PR, I rewrite #33 for task_compiler test.

This original PR seems to include
 ```
pddl/pddl_planner/demos/simple_failure_torelant/demo_simple_failure_torelant.launch
pddl/pddl_planner/demos/simple_failure_torelant/solve-simple-failure-torelant.l
```
but they are not tested. Is it ok?

**Comment by furushchev** [comment]
discussion continued in #33

**Comment by k-okada** [comment]
good, so we can close this PR, now it moved to #34 and #30

**Comment by furushchev** [comment]
*#30 -> #33

**Pull request closed without merging**
