### PR TITLE
add all-relationship graph

### PR DESCRIPTION
**Pull request by h-kamada**
* generate all relationship graph

### CODE REVIEW

**Comment by h-kamada** [comment]
* previous graph (single relationship graph)
singlerelationship


* all relationship graph
allrelationship

**Comment by k-okada** [comment]
@furushchev please review

**Comment by furushchev** [comment]
@h-kamada I don't know what a "relationship graph" is. Could you explain about itself and the difference between a "single" graph and "all" graph?
Also figs you attached are too small to read, please re-attach bigger ones.
About the codes, please add `README.md` that includes description of demo, what is new and the usage. (`jsk_planning/pddl/pddl_planner/demos/2016_kamada_durative/README.md` is good to me to put)

**Comment by h-kamada** [comment]
I wrote example codes and README for explaining the relationship graph.
Please see ->
https://github.com/h-kamada/jsk_planning/tree/add-all-relationship-graph/pddl/pddl_planner/demos/2016_kamada_durative

**Comment by furushchev** [comment]
@h-kamada Thanks. Now as I understand from readme, "all" relation graph is like `verbose` version of "single" graph, right?
If so, could you unify codes that generates graph something like:

```lisp
(defun make-relation-graph (result reltype &key verbose)
  (if verbose
    (make all relationship graph)
   (make single relationship graph)))
```

or

```lisp
(defun make-relation-graph (result reltype &key verbose)
  (let ((graph (make single graph)))
  (when verbose
     (append graph (additional edges)))) ;; make the simple graph all relationship one
```

**Comment by h-kamada** [comment]
I fixed like this.
````
(defun make-relation-graph (result &key verbose)
  (let ((relation-lst
         (cond
          (verbose
           (send (cdr (assoc :state result)) :all-relationship))
          (t
           (send (cdr (assoc :state result)) :relationship))))
````

**Comment by furushchev** [comment]
@h-kamada Thanks.
- Could you append `[pddl_planner] ` to the commit name?
- Could you add test for the repository?

**Comment by h-kamada** [comment]
fixed!

**Comment by furushchev** [comment]
test failed.

```bash
output to /home/travis/.ros/test_results/pddl_planner/rosunit-test_2016_kamada_durative.xml
start testing [test-2016-kamada-durative]
waiting pddl_planner
get actionlib server
sent goal
waiting goal...
[INFO] [WallTime: 1476938046.227302] take a message
[INFO] [WallTime: 1476938046.227978] gen_tmp_pddl_file: requirements::typing :durative-actions :adl
[INFO] [WallTime: 1476938046.228983] domain.actions:[name: pick
parameters: (?robot - robot ?obj - object ?underobj - object)
precondition: (and (at start (not (working ?robot))) (over all (at-robot ?robot table)) (over all (not (on ?obj cup))) (over all (not (on ?obj dish))) (at start (on ?underobj ?obj)))
effect: (and (at start (working ?robot)) (at end (not (working ?robot))) (at end (not (on ?underobj ?obj))))
on_condition: ''
action_duration: (= ?duration 10), name: movetoTABLE
parameters: (?robot - robot)
precondition: (and (at start (not (working ?robot))) (at start (not (at-robot ?robot table))))
effect: (and (at start (working ?robot)) (at end (not (working ?robot))) (at end (at-robot ?robot table)))
on_condition: ''
action_duration: (= ?duration 1)]
[INFO] [WallTime: 1476938046.229707] problem_path => /tmp/problem_rqKtSq
[INFO] [WallTime: 1476938046.230224] domain_path => /tmp/domain_Rshkqs
[INFO] [WallTime: 1476938046.230575] lpg
[INFO] [WallTime: 1476938046.274432] [rospack] Error: package 'lpg_planner' not found
[ERROR] test (or (equal last-state '(((at-robot robot1 table)))) (equal last-state '(((at-robot robot2 table)))) (equal last-state '(((at-robot robot1 table) (at-robot robot2 table)))) (equal last-state '(((at-robot robot2 table) (at-robot robot1 table))))) failed ... (goal state ^[0mmwaiting goal...
rver
016-kamada-durative]
ddl_planner/rosunit-test_2016_kamada_durative.xml
g�).
```

**Comment by h-kamada** [comment]
I think jsk-ros-pkg/jsk_3rdparty#70 is needed for running lpg_planner.

**Comment by furushchev** [comment]
@h-kamada OK. Then let's wait jsk-ros-pkg/jsk_3rdparty#70 .

**Comment by k-okada** [comment]
since lpg_planner is not included in deb file, I think we can not test this package on travis. see https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/70/files#diff-3b38005fd1272a85a60022411b84ac4aR10

**Comment by h-kamada** [comment]
OK. So, in this case, what should I do for passing travis check?

**Comment by k-okada** [comment]
how about , if lpg_planner is not found, show error and exit, 
```
[INFO] [WallTime: 1476938046.274432] [rospack] Error: package 'lpg_planner' not found
```
or change suffix of test file from `.test` to `.launch` may works.
I think `2016-kamada` should be add one more word to explain what are you going to plan. like 'kitch', or 'cleanup', 'setup table' ...

**Comment by h-kamada** [comment]
> I think 2016-kamada should be add one more word to explain what are you going to plan. like 'kitch', or 'cleanup', 'setup table' ...

@k-okada , are you meaning that the directory name of `2016_kamada_durative` should be a more detailed?

**Comment by k-okada** [comment]
No, I mean `pddl/pddl_planner/test/test-2016-kamada-durative.test`,  test-durative-two-robot-tablecloth-test ?

**Comment by h-kamada** [comment]
fixed to `test-durative-two-robot-tablecloth.test`

**Comment by h-kamada** [comment]
fixed test (for passing travis test)

**Pull request merged**
