### PR TITLE
[task_compiler] add task_compiler test

### PR DESCRIPTION
**Pull request by k-okada**
this is rebased version of #30
- task_compiler/test: add test/dummy-action.l, test/test-task-compiler.l test/test_task_compiler.test
- task_compiler/launch/execute-pddl.launch: add arg gui

### CODE REVIEW

**Comment by k-okada** [comment]
need to wait for https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/43

**Comment by k-okada** [comment]
wait for https://github.com/ros/rosdistro/pull/9874

**Comment by furushchev** [comment]
> This original PR seems to include
> 
> pddl/pddl_planner/demos/simple_failure_torelant/demo_simple_failure_torelant.launch
> pddl/pddl_planner/demos/simple_failure_torelant/solve-simple-failure-torelant.l
> but they are not tested. Is it ok?

Added test on `pddl_planner` package. #34 
 Test on this PR needs #34

**Comment by k-okada** [comment]
good, so we can close this PR, now it moved to #34 and #30

**Comment by k-okada** [comment]
failed...
```
+++catkin_test_results --verbose --all /home/travis/.ros/test_results
Full test results for 'task_compiler/rosunit-test_task_compiler.xml'
-------------------------------------------------

  
  
  
   
Test:(eq (length *msg*) 7)
Trace:" (length *msg*) is 0test-task-compiler]
sults/task_compiler/rosunit-test_task_compiler.xml
15  1.0.10))
?7Ã?"
Message:""
   
  


-------------------------------------------------
pddl_planner/rosunit-test_simple_failure_torelant.xml: 1 tests
task_compiler/rosunit-test_task_compiler.xml: 1 tests, 0 errors, 1 failures
Summary: 2 tests, 0 errors, 1 failures
```

**Comment by furushchev** [comment]
To rebase another branch to this PR is a bit complex, so I created another PR based on the latest master branch
https://github.com/jsk-ros-pkg/jsk_planning/pull/35

**Comment by furushchev** [comment]
@k-okada overdriven PR was merged. so I think it's ok to close this PR. Thanks.

**Pull request closed without merging**
