### PR TITLE
[pddl_planner] add test for pddl_planner

### PR DESCRIPTION
**Pull request by furushchev**

### CODE REVIEW

**Comment by furushchev** [comment]
I used the code of `roseus_smach`. So removed its codes and now this pr should passes.

**Comment by furushchev** [comment]
still not passed on hydro.

```
Test:(equal (car (last step-state)) '((at elevator) (found elevator-button) (light elevator-button)))
Trace:"ant]
_planner/rosunit-test_simple_failure_torelant.xml
0))
??Â¤?).?[0m
nitial state ?[0mmwaiting goal...
rver
imple-failure-torel"
Message:"goal state"
   
   
Test:(equal (car step-state) '((at start)))
Trace:"?[0mmwaiting goal...
rver
imple-failure-torelant]
_planner/rosunit-test_simple_failure_torelant.xml
0))
??Â¤?"
Message:"initial state"
```

**Comment by furushchev** [comment]
ok. now test passed.

**Comment by k-okada** [comment]
how about add
```
<build_depend>time</build_time> <!-- downward depends on time, but on hydro it is not released -->
```
to package.xml, ?

**Comment by furushchev** [comment]
@k-okada thank you for advice. I created PR.

**Comment by k-okada** [comment]
sorry, i meant to put depend to time in pddl_plannr, maybe run_depends is
better than build_depends...

--
◉ Kei Okada

**Comment by furushchev** [comment]
@k-okada OK. Commited on this PR, Closed previous another PR.

**Comment by k-okada** [comment]
thanks, then you can remove EXTRA_DEB from .travis.yml

**Comment by furushchev** [comment]
I already removed.

**Comment by furushchev** [comment]
ok. now test passed.

**Comment by furushchev** [comment]
@k-okada Thanks.

**Pull request merged**
