### PR TITLE
[pddl_planner&task_compiler] add test for task_compiler hook functions

### PR DESCRIPTION
**Pull request by furushchev**
required https://github.com/jsk-ros-pkg/jsk_roseus/pull/460

### CODE REVIEW

**Comment by furushchev** [comment]
now travis passed.
@k-okada Please merge if there is no problem.

**Comment by furushchev** [comment]
@k-okada Thank you for very much!

**Comment by furushchev** [comment]
@k-okada Could you please release this repository?

**Comment by k-okada** [comment]
ok, how about include https://github.com/jsk-ros-pkg/jsk_planning/pull/48
and https://github.com/jsk-ros-pkg/jsk_planning/pull/49 in next release?

--
◉ Kei Okada

**Pull request merged**
